title: Unity Roleplay Rules
description: Official rules and legal documentation for Unity RP.
theme: just-the-docs

url: https://<your-username>.github.io/unity-rp-rules

search_enabled: true
color_scheme: dark
